services:
  frontend:
    image: nginx:alpine
    container_name: helloworld_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 2

  backend:
    image: node:22-alpine
    container_name: helloworld_backend
    working_dir: /app
    volumes:
      - ./backend:/app:ro
    command: yarn start:prod
    env_file:
      - docker/backend/env
    environment:
      NODE_ENV: production
      PORT: 4000
    expose:
      - 4000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 2

networks:
  default:
    external: true
    name: apps
