services:
  frontend:
    image: ghcr.io/burtek/dtrw-app-helloworld/frontend:${VERSION_TAG}
    container_name: helloworld_frontend
    restart: unless-stopped
    environment:
      API_URL: http://helloworld_backend:4000
    healthcheck:
      test: curl -f http://localhost/
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 5s
      start_interval: 5s
    networks:
      - default
      - apps

  backend:
    image: ghcr.io/burtek/dtrw-app-helloworld/backend:${VERSION_TAG}
    container_name: helloworld_backend
    environment:
      PORT: 4000
    env_file:
      - path: .backend.env
        required: false
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:4000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 25s
      start_interval: 10s
    networks:
      - default

networks:
  default:
    internal: true
  apps:
    external: true
    name: apps
