services:
  frontend:
    image: nginx:alpine
    container_name: helloworld_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  backend:
    image: node:22
    container_name: helloworld_backend
    working_dir: /app
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    command: node src/main.js
    environment:
      NODE_ENV: production
      PORT: 4000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    external: true
    name: apps
