name: Build alpine artifact

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
      node-version:
        required: true
        type: string
      upload-artifact:
        required: false
        type: boolean
        default: false
      artifact-retentions-days:
        required: false
        type: number
        default: 3

permissions:
  contents: read

jobs:
  build-alpine:
    name: Build assets on Alpine Linux
    runs-on: ubuntu-latest
    container:
      image: node:26-alpine
    env:
      BUILD_SHA: ${{ inputs.ref }}
    steps:
      - id: prepare-alpine
        name: Add tar for caching and python to build dependencies
        run: apk add --no-cache tar python3 py3-pip build-base
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}
      - id: setup-node
        name: Setup node with pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ inputs.node-version }}
          install-deps: true
          shell: sh
      - id: tests
        name: Run tests
        run: pnpm test
        background: true
      - id: build
        name: Build
        run: pnpm stage
        background: true
      - id: wait
        name: Wait for background jobs to finish
        wait: [tests, build]
      - id: pack-artifacts
        name: Pack artifacts
        run: |
          tar -czf alpine-build-output.tar.gz docker docker-compose.yml packages/*/.assembled --transform='s,^packages/\(.\+\)/.assembled,\1,'
      - id: upload-artifact
        if: inputs.upload-artifact == 'true' || inputs.upload-artifact == true
        name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: alpine-build-output.tar.gz
          retention-days: ${{ inputs.artifact-retentions-days }}
