name: Deploy App to VPS

permissions:
  contents: read

on:
  push:
    branches:
      - master

env:
  APP_NAME: helloworld

jobs:
  test_ssh:
    name: Test SSH connection to VPS
    runs-on: ubuntu-latest

    concurrency:
      group: deploy1-${{ github.ref }}
      cancel-in-progress: true
  
    if: >
      !contains(github.event.head_commit.message, 'chore(release)') &&
      !contains(github.event.head_commit.message, 'chore: release') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci-skip]') &&
      !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Test SSH
        uses: burtek/setup-ssh@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          alias: production
          test_connection: true

  release:
    name: Create release commit and tag
    runs-on: ubuntu-latest
    needs: test_ssh

    concurrency:
      group: deploy2-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: write

    outputs:
      version: ${{ steps.output_version.outputs.version }}
      release_commit_sha: ${{ steps.output_version.outputs.release_commit_sha }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Needed for standard-version to access tags

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26.5
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - id: tests
        name: Run tests
        run: pnpm test
        background: true

      - id: lint
        name: Run lint
        run: pnpm lint
        background: true

      - id: build
        name: Build
        run: pnpm build
        background: true

      - name: Wait for background jobs to finish
        wait: [tests, lint, build]

      - name: Bump version and generate changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pnpm release

      - id: push
        name: Push release commit and tags
        uses: ad-m/github-push-action@master
        with:
          branch: master
          tags: true
        background: true

      - id: output_version
        name: Output new version and release commit sha
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
          echo "release_commit_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        background: true

      - name: Wait for background jobs to finish
        wait: [push, output_version]

  deploy:
    name: Deploy to VPS
    needs: release
    runs-on: ubuntu-latest

    concurrency:
      group: deploy3-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ needs.release.outputs.release_commit_sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26.5
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - name: Run tests
        run: pnpm test

      - name: Build all packages
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> docker/backend/env
          VITE_COMMIT="$COMMIT_SHA" pnpm deploy

      - id: setup-ssh
        name: Test SSH
        uses: burtek/setup-ssh@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          alias: production
          test_connection: true

      - id: deploy-files
        name: Deploy build files
        run: |
          tar czf - dist-frontend dist-backend docker docker-compose.yml |
          ssh production '
              set -eu

              rm -rf /apps/${{ env.APP_NAME }}/upload /apps/${{ env.APP_NAME }}/old
              mkdir -p /apps/${{ env.APP_NAME }}/upload
              tar xzf - -C /apps/${{ env.APP_NAME }}/upload
          '

      - id: start-app
        name: Replace files and start new version of the app
        run: |
          ssh production '
              set -euo pipefail
              
              cd /apps/${{ env.APP_NAME }}
              if [ -f docker-compose.yml ]
              then
                docker compose stop
              fi

              rm -rf old
              mkdir -p old

              [ -f docker-compose.yml ] && mv docker-compose.yml old/
              [ -d docker ] && mv docker old/
              [ -d frontend ] && mv frontend old/
              [ -d backend ] && mv backend old/

              mv upload/docker-compose.yml docker-compose.yml
              mv upload/docker docker
              mv upload/dist-frontend frontend
              mv upload/dist-backend backend
              rmdir upload

              docker compose up -d
          '
