name: Deploy App to VPS

permissions:
  contents: read

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: helloworld

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26.5
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - name: Run tests
        run: pnpm test

      - name: Build all packages
        run: |
          echo "COMMIT_SHA=${{ github.sha }}" >> docker/backend/env
          VITE_COMMIT=${{ github.sha }} pnpm deploy

      - name: Deploy docker configs
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          source: "docker,docker-compose.yml"
          target: "/apps/${{ env.APP_NAME }}/docker.new"

      - name: Deploy frontend
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          source: "dist-frontend/*"
          target: "/apps/${{ env.APP_NAME }}/frontend.new"
          strip_components: 1

      - name: Deploy backend
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          source: "dist-backend/*"
          target: "/apps/${{ env.APP_NAME }}/backend.new"
          strip_components: 1

      - name: Swap new and old directories and start docker containers
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            mkdir -p /apps/${{ env.APP_NAME }}
            cd /apps/${{ env.APP_NAME }}
            if [ -f docker-compose.yml ]
            then
              docker compose stop
            fi

            rm -rf docker.old frontend.old backend.old docker-compose.old.yml

            [ -f docker-compose.yml ] && mv docker-compose.yml docker-compose.old.yml
            [ -d docker ] && mv docker docker.old
            [ -d frontend ] && mv frontend frontend.old
            [ -d backend ] && mv backend backend.old
            
            mv docker.new/docker-compose.yml .
            mv docker.new/docker .
            rmdir docker.new
            mv frontend.new frontend
            mv backend.new backend

            docker compose up -d

            rm -rf docker.old frontend.old backend.old docker-compose.old.yml
