name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26.5
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - id: tests
        name: Run tests
        run: pnpm test
        background: true

      - id: lint
        name: Run lint
        run: pnpm lint
        background: true

      - id: build
        name: Build
        run: pnpm build
        background: true

      - name: Wait for background jobs to finish
        wait: [tests, lint, build]
